### ISSUE TITLE
Create Intro Document

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/Unity-Mentorship-2021#12]
Acceptance Criteria: Create and commit a markdown (.md) document containing the following information:

1. Your name.

2. Do you plan to leverage Bolt?

3. An idea that you have for the project.

4. Your desired tech stack for the project.

**Comment by gavinjalberghini** [comment]
V: 2

**Comment by Nathan-the-berliner** [comment]
1. Nathan Babcock

**Comment by Nathan-the-berliner** [comment]
Is this where I put my response

**Comment by gavinjalberghini** [comment]
@Nathan-the-berliner You should first install Git and clone the repo. Once that is done you should create a markdown file (extension .md). Fill out the file as per the instructions above. Then commit and push the file.

**Comment by JasonGG03** [comment]
[Week 1 Task - Jason Gallardo Gonzalez.md](https://github.com/gavinjalberghini/Unity-Mentorship-2021/files/6812673/Week.1.Task.-.Jason.Gallardo.Gonzalez.md)

**Comment by AHicks2004** [comment]
[Week 1 task.docx](https://github.com/gavinjalberghini/Unity-Mentorship-2021/files/6814004/Week.1.task.docx)

**Comment by gavinjalberghini** [comment]
Verified that everyone can commit and push to repo.
