### ISSUE TITLE
Decide on theme and workflow for hub world

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/Unity-Mentorship-2021#34]
Acceptance Criteria: The team has a clear theme for the game and knows how they want to integrate and design the hub world. 

V:2

**Comment by gavinjalberghini** [comment]
Follow on meeting after 7/28 sprint review. Items to discuss: What is the theme of the hub world? Is it in any way associated with the minigames? How will a player move from the hub world into a minigame? Who will work on the hub world? Is there anything to do in the hub world other than move into a minigame?

**Comment by Nathan-the-berliner** [comment]
I created my own branch.

**Comment by Nathan-the-berliner** [comment]
I created my own git hub branch.

**Comment by AHicks2004** [comment]
In the ideas channel in discord we sent three pictures. What we were thinking is taking bits and pieces from each of the different hubs and incorporate them into ours. So we have not decided to use just one but we've decided to merge them all together in a sense.

**Comment by AHicks2004** [comment]
A hub world with portals that allow you the enter each mini game. And, a separate map select where the player can select a level without having to walk over to it.
