### ISSUE TITLE
Watch bolt videos

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/Unity-Mentorship-2021#36]
Acceptance Criteria: Watch the videos:
https://www.youtube.com/watch?v=1YtnRkeicHY&t=1s
https://www.youtube.com/watch?v=wqwOtWpEDfM
https://www.youtube.com/watch?v=KsMUhUlNuho

Please post on this issue thread when you have watched the videos.

V:2

**Comment by mileslomanno** [comment]
I watched the videos
